### PR TITLE
fatkid_submarine let's try this again

### PR DESCRIPTION
**Pull request by CodyThe**
Edit: Making this look more professional

fatkid_submarine is the map I worked on a few months ago and then abandoned because I lost the drive to make maps, I have found that drive again and I hope to explain this in depth

image

This is the starting area, behind where the players spawn is the last area of the map, the reds I hope display a sense of danger to the player and makes newbies run forward, the fat-kid is in the kitchen which I thought would fit better.

image

This is the second room, it's a gas area which I assume would give oxygen to the submarine, the cage is a skeleton teleport, and I had a custom message displayed for when skinny kids/fat-kid tries to go through it, the use of the gravity gun I hope is an interesting game mechanic, the lighting here is flat, and a yellow tinted white.

image

image

This section of the hallway gives the skinny kids shotguns and pistols, I thought of the decision for game=balance but realized that I had to give them shotguns earlier than usual due to the choke-y nature of the map _**(What bloodstains?).**_

image

The second section of the hallways, this also has the second teleport and leads to a staircase which I consider to be the halfway point of the map, not much else to say.

image

(Don't mind the boxes being down, the screenshots were taken on sandbox game-mode.) This is the part where skinny kids have the high-ground if skeletons don't decide to teleport, I gave them SMG's for this reason.

image

Just simple prop detail as filler to give the fat-kid more time to catch up the humans

image

Ditto ^

image

Last part of the map, a window shows the void (meaning that they are very deep underwater). I think it adds to the comical-nature of the game-mode and the intensity of the situation.

image

I made this area almost pitch black to give the player a sense of dread, as this is a good camping spot for the fat-kid, and makes the player look back on what they did to get to this point.

Pretty proud of this map, and hopes this gets added to the game, I hope you liked the sort of director's commentary that I did here as well.

### CODE REVIEW

**Comment by CodyThe** [comment]
Added a few details like a room with a zombie in it (They can't get out of the room since it is boarded with wood.), and a few windows showing the "water".

**Comment by alao3alao3** [comment]
Theres a few problems with the functionality of the map:
The map leaks all over. When you make the map make sure your brushes and stuff snap to the grid. Try and use the vertex tool to have diagonal brushes instead of just rotating the brush.
apng
Alot of the leaks look like that, atleast the ones I can find. I tried to fix all of them but simply couldn't. The map has to be sealed.

Do not use the void as a form of decor, it will mess with the lighting among other issues. If you want the outside to be black, use the material tools/toolsblack and place a brush outside the windows.

Make the brushes that are being used only as details (they do not seal the map from the void) as the func_detail entity, such as the frame to the teleporter or the wooden planks blocking the zombie. This is just good for optimization and a good habit to develop.

Ceilings and floors do not have to be the same shape as the room they cover. This is what I believe led to the various leaks, along with brushes just not being aligned to the grids.

Displacements do not seal the map (the window with the dirt outside of it and the Annabelle) and only one face of a brush needs to be made into a displacement. Seal the dirt room with proper brushes.

Not a functionality problem but teleporter exits should be more clearly marked or indicated, such as like a pad on the floor or something so the exit doesn't appear arbitrary.

The map may need to be extensively redone due to the leaks that span multiple areas of the map. The layout itself is probably fine being just a hallway, which is essentially what Gymnasium is.

**Comment by CodyThe** [comment]
Thanks for the feedback, will get to work on this immediately, my lazy copy and pastes of the floor to the roof caused the leaks probably, If I need to re-do the entire map I actually have graph paper layouts to work off of.

**Comment by CodyThe** [comment]
Imma close this due to the fact that I have to redo the entire map, this is gonna take awhile.

**Pull request closed without merging**
