### PR TITLE
Adds New Fatkid Map: Fatkid Bunker

### PR DESCRIPTION
**Pull request by alao3alao3**
Is there any code calling the map file? I've just put the files in where everything else was, I have no idea if the server will decide to load it. I can't find any code that calls map files or the folder they're in so this might be fine.
## Intent
Adds a new Fatkid map: Fatkid Bunker
Notice: Images may be outdated following recent changes to the map.
fatkid_bunker0001
fatkid_bunker0002
fatkid_bunker0003
fatkid_bunker0004
fatkid_bunker0005

Fatkid Bunker is a very close quarters, short, and linear map that features 550 health barricades, climaxing on a circular area that gives multiple paths of attack for skeletons and allowing players to traverse the full rim, provided the barricades are broken.

**Backstory:** The whole class has been invited to a housewarming party in celebration of the purchase of a faraway ranch house by a fellow classmate. The whole class, except Gregory, of course. The barring of entry to a catered event however is a mortal sin in the eyes of any fatass and not taken kindly. Not one to leave empty handed, Gregory descends into a voracious frenzy, forcing the atendees to flee into the nearby bunker the seller explicitly stated should not be entered under any circumstance.

Further tweaking can be done if the barricades are broken too fast, or if certain chokepoints are too strong.

## Why Is This Good For The Game
Having a new map is always good for the game, especially with the sparse selection we have currently.

### CODE REVIEW

**Comment by PYROTEKNIK** [comment]
yo this looks fuckin based

**Comment by alao3alao3** [comment]
thanks

**Comment by swampservers** [comment]
Looks good to me as well, someone needs to review it in detail though

**Comment by PYROTEKNIK** [comment]
also generally servers tend to add maps to the vote based on map prefixes i believe. you should be good to go without any code changes. If it's not inserted automatically, swamp probably sticks them in a list somewhere

**Comment by alao3alao3** [comment]
ah alright

**Comment by swampservers** [comment]
@TrenerMiecinek

**Comment by TrenerMiecinek** [comment]
im on it

**Comment by TrenerMiecinek** [comment]
1. In the first part of the map it would be cool to mark the invisible walls with a fence so it doesn't look weird.

2. This skeleton passage has invisible wall till the 2nd layer of the boxes is broken so it's not opened for skeletons, in my opinion it should be opened after the doors are broken so skeletons can ambush the skinny kids. 

3. All of the boxes in the last part of the map can be skipped by climbing over them and after breaking any layer of them there is an invisible wall behind them.

4. The grenades in the 'gas chamber' cannot be picked up, they just trigger and explode after trying to do so. 

5. Also this weird texture appears next to the bunker entrance.

**Comment by alao3alao3** [comment]
Fixed and added the fences along with a bit more decor, you can take another look at it now.

Also the playerclips that were with the barricades in the final section have been changed to func_skeletonpasses with targetnames associated with their respective barricades. I'm not familiar with the entity but it should work as normal and remove itself once a barricade is destroyed.

**Comment by TrenerMiecinek** [comment]
Just add a gate here and I think everything is ok.

**Comment by alao3alao3** [comment]
I've added the fence and changed the brushes at the end to be skeletongates instead of skeletonpasses (so the humans cant fit there message won't show up). Moreover the brushes are named differently and killed when the barricade is destroyed, as destroying the barricade initially did not remove skeletonpasses when they were named barricade0X.

Gmod isn't working for some goddamn reason on my end so you may want to play this map on a server with the gamemode running to verify if the last barricades really break. I'm sorry I cannot test it myself right now.

**Comment by alao3alao3** [comment]
forgot the trees and crane, was able to test it and the func_skeletongates removed themselves, this version should be ready to merge

**Comment by TrenerMiecinek** [comment]
@swampservers it's ready

**Comment by swampservers** [comment]
Thank you!

**Pull request merged**
