### PR TITLE
New map?

### PR DESCRIPTION
**Pull request by CodyThe**
Uh shit, put the files in the wrong place. You can still look at them though.

### CODE REVIEW

**Comment by CodyThe** [comment]
Moved maps to the maps folder, might update the maps if I see fit.

**Comment by alao3alao3** [comment]
It'd be nice to get some pics of it so people wouldn't have to download the vmf or bsp to see it

**Comment by swampservers** [comment]
1. Where are the crowbars?
2. All the barricades are right at the start when the skinnykids have the weakest weapons. The barricades should get more common at the end, not at the start, they will stand no chance on this map.
3. So the map is like a loop shape, but at the end there is just a jarring teleporter that takes you back to the start? Were you just too lazy to make a staircase down and a door that opens when the players get close enough to it from the other side?
4. Make the lighting not look like garbage, some surfaces are literally pitch black. In the future please do not submit obviously unfinished work like this.

**Comment by swampservers** [comment]
> It'd be nice to get some pics of it so people wouldn't have to download the vmf or bsp to see it

Not necessary, we need to look at the map file anyway

**Comment by CodyThe** [comment]
Firstly, crowbars are at the start, secondly this is not a finished product as I just wanted to hear some feedback on it. Thank you, and I will fix the lighting and the teleporters.

**Comment by CodyThe** [comment]
Also sorry if the map looked lazy.

**Comment by CodyThe** [comment]
Hopefully fixed it now!

**Comment by swampservers** [comment]
Sorry, I messed with the repo, and it's not letting me reopen/merge this PR. I think you'll need to back up your work, delete and recreate your fork on github, and then commit again and open a new PR. Also please add a backstory as described in the updated Readme.

**Comment by CodyThe** [comment]
Will do, thanks.

**Pull request closed without merging**
