### PR TITLE
fatkid_subterranean

### PR DESCRIPTION
**Pull request by DaFloppa**
Fatkid_catacombs is a map originally made by some guy named Scott, but I don't know who he really is.

I took the original bsp, decompiled it for the .vmf with the screwed up vertices and aligned them, and started from scratch there.
Just like the original map, it has a lift that traverses a big pit toward the end of the map.

If this gets merged, I will probably include some updates for other maps along with the most likely inevitable bug fixes that I would have to make for this map.

### CODE REVIEW

**Comment by swampservers** [comment]
This looks excellent overall! A few comments:

missing textures:
https://gyazo.com/27b91e88feb515e4a9eb68e39e94adb1 https://gyazo.com/961e9227ac0f2c9b58f130b300bb6550
and on the hanging cart thing

If this hallway is supposed to be carved out stone, its too square: https://gyazo.com/479db8d789dd488f0b16922633e177eb
I also think it's too narrow for good gameplay (too hard to get through as a skeleton)

I think the map could use more secret passages for skeletons. I usually try to make it so there are at least 2 pathways to get into any room, so when skinny kids are focusing on one they have another way to get in rather than dying in the same place over and over. Don't feel constrained by the layout of the old map, it didn't really play that well.

Artistically, I think more of the map should have the "ancient Egyptian tomb" theme, to match the title of the map

**Comment by DaFloppa** [comment]
Okay. I've fixed the missing textures, added a vent from early on so that the skeletons can get to places faster and easier, and widened the 2 passages.

I originally wanted to keep them as displacements, but since they were too square, I couldn't keep them that way because no matter how I tried, I ran into geometric problems with the engine.

I too think that the map name doesn't exactly match it's description, but I couldn't think of any way to really replicate the original map art style with it still making sense. I couldn't even tell at first that the bone texture in the map was bones. I think it will be fine though, because it gives a basic message that the map is underground and a little confined.

**Comment by DaFloppa** [comment]
I've changed the map name to fatkid_subterranean as a temporary name, so that once I'm able to find the time to implement the changes you'd want I can rename it back to fatkid_catacombs.

**Comment by swampservers** [comment]
Looks good, thank you! There is still a missing texture on the cable car but we should start playing this as i'm sure you'll want to change a lot of things

**Pull request merged**
