### PR TITLE
Fat Kid "Mines" map.

### PR DESCRIPTION
**Pull request by Palexite**
originally created by Spök
modified by Golden Boy

### CODE REVIEW

**Comment by swampservers** [comment]
What am I supposed to do, compile it myself?

**Comment by swampservers** [comment]
It is supposed to go in maps/ not in the root dir

**Comment by swampservers** [comment]
@PYROTEKNIK review plz

**Comment by Palexite** [comment]
oh well fuck.
hold on one sec.

**Comment by swampservers** [comment]
Please use all lowercase letters for the filename; also, since these maps are updated through workshop, you can remove the 01 from the end

**Comment by alao3alao3** [comment]
yoo new map

**Comment by swampservers** [comment]
Sorry, I messed with the repo, and it's not letting me reopen/merge this PR. I think you'll need to back up your work, delete and recreate your fork on github, and then commit again and open a new PR. Also please add a backstory as described in the updated Readme.

**Pull request closed without merging**
