### PR TITLE
New "Mines" map. *completed* Ready to be released now!

### PR DESCRIPTION
**Pull request by Palexite**
Created by Spok https://steamcommunity.com/profiles/76561198071656568
 Map originated from -  https://steamcommunity.com/sharedfiles/filedetails/?id=825038140&searchtext=zs+mines
modified by Golden Boy#3489 (Golden Boy) and Alao#9625 (Lozhenge)

We are gaven permission to use this map by Spok.

- Storyline -
"It was a special day for Gregory's class. The teachers scheduled a field trip to the mines.
each student was allowed to bring one snack. Which wasn't enough for Gregory ofcourse. while the class
were waiting for their Tour guide at the mines. Some kids were gossiping about Gregory behind his back.
One told the shy kid to get the biggest rock you can find and chuck it at Gregory's ass. The shy kid
got a pretty dull rock and threw it at Gregory. At that very moment,  something inside his fragile autistic mind snapped.
Or perhaps it was just hunger, as his fat ass hadn't eaten a complete meal in 3 hours.
Either way, he deepthroated the shy kid, and started eating his fellow classmates in a murderous rampage of gluttony..."

### CODE REVIEW

**Comment by PYROTEKNIK** [comment]
please rename and recompile the map with a lowercase map name

**Comment by PYROTEKNIK** [comment]
fatkid_mines010006
fatkid_mines010005
fatkid_mines010004
fatkid_mines010003
fatkid_mines010002
fatkid_mines010001
fatkid_mines010010
fatkid_mines010009
fatkid_mines010007
There are missing textures, please pack these into your bsp file

**Comment by PYROTEKNIK** [comment]
fatkid_mines010008
the areas i've shaded are very out of the way and lead nowhere useful. This is just going to prolong rounds. The train blocking the way is just going to cause people to get redirected to these side paths.
Also the entire map is just way too long and spread out. It seems like it would take the fat kid like half an hour to walk from one end to the other.

**Comment by PYROTEKNIK** [comment]
Quickly editing existing maps to put content in for the sake of it isn't a very smart plan. If you don't make something worth playing on, people are just not going to vote for it.

**Comment by Palexite** [comment]
are you suggesting we should just scrap this? im okay with that. or could I fix these? the problem is this map is for another gamemode that usually uses CSS resources. I could easily replace these textures.

**Comment by swampservers** [comment]
you need to test the map on a fresh gmod install to ensure there are no missing textures. use CompilePal, QuickPack, or whatever to put all the assets into the map

**Pull request closed without merging**
