### PR TITLE
3rd pull request for this shit since the fork keeps getting borked.

### PR DESCRIPTION
**Pull request by CodyThe**
Fixed lighting

Fixed stair texture

Changed the barricades to prop_physics.

### CODE REVIEW

**Comment by CodyThe** [comment]
Hold on, the new backstory didn't save.

**Comment by swampservers** [comment]
Sorry, someone was supposed to look at this

**Comment by TrenerMiecinek** [comment]
Sorry for delay.
1. Could you make it more obvious where the skeleton teleport is? Something like marking it with lines would be ok. 
2. I think lighting is still kind of messed up after first and second wall of boxes.
3. Change the angle of the "Ravenholm" sign, because right side of it is inside a wall.
4. I like the backstory, It's pretty funny.

**Comment by swampservers** [comment]
Not updated

**Pull request closed without merging**
